image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  GCP_PROJECT_ID: oxocard
  BLOCKLY_BUILDER_IMAGE_NAME: oxocard-api-builder
  BLOCKLY_BUILDER_IMAGE: eu.gcr.io/$GCP_PROJECT_ID/$BLOCKLY_BUILDER_IMAGE_NAME

stages:
- build_builder
- build

build_blockly_component_builder_image:
  stage: build_builder
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t $BLOCKLY_BUILDER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $BLOCKLY_BUILDER_IMAGE_NAME:latest -f BuilderDockerfile .
    - echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://eu.gcr.io
    - docker push  $BLOCKLY_BUILDER_IMAGE_NAME:latest
    - docker push $BLOCKLY_BUILDER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  when: manual


build_blockly_compoent:
  stage: build
  image: docker:stable
  services:
  - docker:dind
  script:
  - echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://eu.gcr.io
  - docker pull $BLOCKLY_BUILDER_IMAGE_NAME:latest
  - docker run -v "$(pwd):/app/blockly/" $BLOCKLY_BUILDER_IMAGE_NAME:latest
  artifacts:
    paths:
    - blockly_compressed.js
    - blockly_uncompressed.js
    - arduino_compressed.js
    - msg/js/**/*.js
    expire_in: 1 week
  only:
  - master